---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`longhorn.k3s.hackbox.cc`)
    kind: Rule
    services:
    - name: longhorn-frontend
      namespace: longhorn-system
      kind: Service
      port: 80
  tls: {} # use TLS store default certificate
