---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    logs:
      access:
        enabled: true
        format: common
    providers:
      kubernetesGateway:
        enabled: false
        experimentalChannel: true
      kubernetesIngress:
        enabled: true
      kubernetesCRD:
        enabled: true
    ports:
      postgresql:
        expose:
          default: true
        port: 5432
        exposedPort: 5432
        protocol: TCP
        tls:
          enabled: true
      rediss:
        expose:
          default: true
        port: 6379
        exposedPort: 6379
        protocol: TCP
        tls:
          enabled: true

