---
all:
  children:
    proxmox:
      hosts:
        donner:
          ansible_host: donner.hackbox.cc
          os: Proxmox
        wetter:
          ansible_host: wetter.hackbox.cc
          os: Proxmox
        vars:
          ansible_user: service
    wireguard:
      hosts:
        mikrus:
          ansible_host: wg.hackbox.cc
          ansible_port: 10122
          ansible_user: service
    k3s_cluster:
      children:
        server:
          hosts:
            supervisor:
              ansible_host: supervisor.hackbox.cc
        agent:
          hosts:
            alpha:
              ansible_host: alpha.hackbox.cc
            bravo:
              ansible_host: bravo.hackbox.cc
            charlie:
              ansible_host: charlie.hackbox.cc
            delta:
              ansible_host: delta.hackbox.cc
      vars:
        extra_server_args: "--secrets-encryption"
        k3s_version: "v1.35.3+k3s1"
        api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
        ansible_user: service
        ansible_port: 22
    debian_hosts:
      hosts:
        mikrus:
        supervisor:
        alpha:
        bravo:
        charlie:
        delta:
        donner:
        wetter:
