---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: bouncer
  namespace: prometheus-stack
spec:
  scheme: HTTP
  staticConfigs:
    - labels:
        job: bouncer
      targets:
        - bouncer.hackbox.cc:9100
