---
apiVersion: monitoring.coreos.com/v1
kind: ScrapeConfig
metadata:
  name: bouncer
  namespace: prometheus-stack
spec:
  scheme: HTTP
  staticConfigs:
    - labels:
        job: prometheus
      targets:
        - bouncer.hackbox.cc:9100
