---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-stack-grafana
  namespace: prometheus-stack
data:
  grafana.ini: |-
    [analytics]
    check_for_updates = true
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = 'grafana.k3s.hackbox.cc'
    root_url = 'https://grafana.k3s.hackbox.cc'
    [unified_storage]
    index_path = /var/lib/grafana-search/bleve
