---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: mikrus
  namespace: prometheus-stack
  labels:
    prometheus: scrape-config
spec:
  scheme: HTTP
  staticConfigs:
    - labels:
        job: mikrus
      targets:
        - mikrus.hackbox.cc:9100
    - labels:
        job: alloy
      targets:
        - mikrus.hackbox.cc:12345
    - labels:
        job: wireguard
      targets:
        - wireguard.hackbox.cc:8787
