---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: valkey
  namespace: kube-system
spec:
  version: 0.9.4
  chart: valkey
  repo: https://valkey.io/valkey-helm/
  targetNamespace: valkey
  createNamespace: true
  valuesContent: |-
    dataStorage:
      enabled: true
      className: longhorn-pg
      requestedSize: 1Gi
    auth:
      enabled: true
      usersExistingSecret: "valkey-users"
      aclUsers:
        default:
          permissions: "~* &* +@all"
          passwordKey: "admin-password"
        readonly:
          permissions: "~* -@all +@read +ping +info"
          passwordKey: "readonly-password"
        infisical:
          permissions: "~* &* -@all +@connection +@read +@write +@keyspace +@pubsub +@transaction +@scripting +info"
          passwordKey: "infisical-password"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        extraLabels:
          release: prometheus-stack
      exporter:
        args:
        - --redis.addr=rediss://valkey.k3s.hackbox.cc:6379
    tls:
      enabled: false
# FMI: TLS between Traefik and VAlkey needs to be fixed at some point!

