---
apiVersion: v1
kind: Secret
metadata:
  name: valkey-tls
  namespace: valkey
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: valkey-cert
  namespace: valkey
spec:
  secretName: valkey-tls
  usages:
    - server auth
  dnsNames:
    - valkey
    - valkey.valkey
    - valkey.valkey.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
