---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitlab
  namespace: kube-system
spec:
  version: 10.0.1
  chart: gitlab
  repo: http://charts.gitlab.io/
  targetNamespace: gitlab
  createNamespace: true
  valuesContent: |-
    global:
      edition: ce
      gitlabVersion: "19.0.1"
      time_zone: "Europe/Warsaw"
      psql:
        host: postgresql-rw.k3s.hackbox.cc
        port: 5432
        database: gitlab
        username: gitlab
        preparedStatements: false
        databaseTasks: true
        password:
          useSecret: true
          secret: gitlab-postgres
          key: password
      redis:
        host: valkey.k3s.hackbox.cc
        port: 6379
        auth:
          enabled: true
          secret: gitlab-valkey
          key: password
        scheme: rediss
      gatewayApi:
        enabled: false
        installEnvoy: false
        configureCertmanager: false
      appConfig:
        object_store:
          enabled: true
          connection:
            secret: gitlab-s3
            key: s3
        backups:
          bucket: gitlab-backups
          tmpBucket: gitlab-tmp
        lfs:
          enabled: true        
          bucket: gitlab-lfs
          connection:
            secret: gitlab-s3
            key: s3
        artifacts:
          enabled: true        
          bucket: gitlab-artifacts
          connection:
            secret: gitlab-s3
            key: s3
        uploads:
          enabled: true        
          bucket: gitlab-uploads
          connection:
            secret: gitlab-s3
            key: s3
        packages:
          enabled: true
          bucket: gitlab-packages
          connection:
            secret: gitlab-s3
            key: s3
        terraformState:
          enabled: true
          bucket: gitlab-terraform-state
          connection:
            secret: gitlab-s3
            key: s3
        ciSecureFiles:
          enabled: true
          bucket: gitlab-ci-secure-files
          connection:
            secret: gitlab-s3
            key: s3
      registry:
        bucket: gitlab-registry
    redis:
      tls:
        enabled: true
        authClients: false
    installCertmanager: false
    certmanager:
      installCRDs: false
      config:
        enableGatewayAPI: false
    gitlab:
      toolbox:
        backups:
          objectStorage:
            config:
              secret: gitlab-s3
              key: s3
    registry:
      storage:
        secret: gitlab-s3
        key: s3                      
