---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitlab
  namespace: kube-system
spec:
  version: 10.0.1
  chart: gitlab
  repo: http://charts.gitlab.io/
  targetNamespace: gitlab
  createNamespace: true
  valuesContent: |-
    global:
      edition: ce
      gitlabVersion: "19.0.1"
      time_zone: "Europe/Warsaw"
      psql:
        host: postgresql-rw.k3s.hackbox.cc
        port: 5432
        database: gitlab
        username: gitlab
        preparedStatements: false
        databaseTasks: true
        password:
          useSecret: true
          secret: gitlab-postgres
          key: password
      redis:
        host: valkey.k3s.hackbox.cc
        port: 6379
        auth:
          enabled: true
          secret: gitlab-redis
          key: redis-password
        scheme: rediss
    redis:
      tls:
        enabled: true
        authClients: false
